### ISSUE TITLE
FNCS2-ns-allinone-3.22 repo doesn't exist

### ISSUE THREAD

**Issue by InstantChocolate** [FNCS/FNCS-Tutorial#2]
git clone https://github.com/GridOPTICS/FNCS2-ns-allinone-3.22
is not possible as the FNCS2-ns-allinone-3.22 repository does not exist

**Comment by haseeb00001** [comment]
facing same problem.

**Comment by jeffdaily** [comment]
Our ns-3 repos moved to our FNCS organization.

- https://github.com/FNCS/ns-3.26
- https://github.com/FNCS/ns-3.24
- https://github.com/FNCS/ns-3.22

**Comment by jeffdaily** [comment]
The demo has been updated to point to https://github.com/FNCS/ns-3.26.
