### ISSUE TITLE
FNCS-Tutorial: 'GridLAB-D+ns-3 demo'

### ISSUE THREAD

**Issue by BattulaSwathi** [FNCS/FNCS-Tutorial#8]
F1_250_house.txt file has 
" subscribe "precommit:C250_i.proxy_clear_price <- ns3_1/F1_250_house/Market2@C250_i/clearPrice" for an 'i'th node.

1. Does it indicate the price signal communicated from Auction object is exclusively for Node C250_i ?
Is it possible for a node 'j' to subscribe for price from 'Market2@C250_i'?

**Comment by afisher1** [comment]
When developing our use case the auction is essentially broadcasting the clear price along with other properties to all the controllers but we didn't build our communication node in ns3 that represents the auction to differentiate between point to point messages and broadcast messages so we just had the auction object create point to point messages for every controller.

That being said yes you could have multiple controllers subscribe to a single topic it's just that if you are using our ns3 model it wouldn't model the message going to each controller node in the ns3 model.

Andy

On Apr 9, 2017, at 8:51 PM, bswathi9 <notifications@github.com<mailto:notifications@github.com>> wrote:


F1_250_house.txt file has
" subscribe "precommit:C250_i.proxy_clear_price <- ns3_1/F1_250_house/Market2@C250_i/clearPrice" for an 'i'th node.

  1.  Does it indicate the price signal communicated from Auction object is exclusively for Node C250_i ?
Is it possible for a node 'j' to subscribe for price from 'Market2@C250_i'?

**Comment by BattulaSwathi** [comment]
Thank you very much for the detailed explanation.
